Repository clubgamma/Awesome-Web-Art, pull requests merged in 2020-10, with the labels that each got.

#3 krish-pabani
  README.md
  krish-pabani/animation2.html
Labels: hacktoberfest2020

#4 AyushSojitra
  AyushSojitra/Share_button.html
  README.md
Labels: hacktoberfest2020

#5 darshvaghasia12
  README.md
  darshvaghasia12/FrameAnimation.html
Labels: hacktoberfest2020

#6 MananJoshimj 3D Animation 1
  MananJoshimj/3D Animation.html
  README.md
Labels: hacktoberfest2020

#7 YashMakadiya123 3D-Animation_revolve
  README.md
  YashMakadiya123/3D-Animation_revolve.html
Labels: hacktoberfest2020

#14 YashMakadiya123
  README.md
  YashMakadiya123/3D-Animation_cube.html
Labels: hacktoberfest2020

#10 AyushSojitra
  AyushSojitra/third_animation.html
Labels: hacktoberfest2020

#12 AyushSojitra
  AyushSojitra/search_button_animated.html
  README.md
Labels: hacktoberfest2020

#16 YashMakadiya123
  README.md
  YashMakadiya123/3D-Animation_cubeslider.html
Labels: hacktoberfest2020

#17 imjp9
  README.md
  imjp19/clock.html
  imjp19/clock.png
  imjp19/ezgif.com-gif-maker (1).gif
  imjp19/style1.css
Labels: hacktoberfest2020

#21 smit4297
  README.md
  smit4297/index.css
  smit4297/index.html
  smit4297/index.js
  smit4297/smit4297.gif
Labels: hacktoberfest2020

#23 MananJoshimj
  MananJoshimj/Animation2.html
  README.md
Labels: hacktoberfest2020

#27 jerry2501
  README.md
  jerry2501/index.html
  jerry2501/jerry2501.gif
  jerry2501/style.css
Labels: hacktoberfest2020

#26 sanketchaudhari10
  README.md
  sanketchaudhari10/animationpage.css
  sanketchaudhari10/animationpage.html
  sanketchaudhari10/animationpagegif.gif
Labels: hacktoberfest2020

#24 thevrajshah
  README.md
  thevrajshah/Accordian.gif
  thevrajshah/Accordian.html
  thevrajshah/Glitch.gif
  thevrajshah/Glitch.html
  thevrajshah/Name.gif
  thevrajshah/Name.html
Labels: hacktoberfest2020

#34 kashyap-shah
  README.md
  kashyap-shah/loading-animation/Loading_Animation.gif
  kashyap-shah/loading-animation/animation.html
Labels: hacktoberfest2020

#33 SmitShah090
  README.md
  SmitShah090/Music Player/EDU_HUB
  SmitShah090/Music Player/index.css
  SmitShah090/Music Player/index.html
  SmitShah090/Music Player/index.js
Labels: hacktoberfest2020

#35 JayMandaviya
  JayMandaviya/button.html
  README.md
Labels: hacktoberfest2020

#37 JayMandaviya
  JayMandaviya/cloth.html
  README.md
Labels: hacktoberfest2020

#36 SmitShah090
  README.md
  SmitShah090/Music Player/Edu_Hub
Labels: hacktoberfest2020

#38 JayMandaviya
  JayMandaviya/Name.html
  README.md
Labels: hacktoberfest2020

#39 kashyap-shah
  README.md
  kashyap-shah/Snake Game - JavaScript/Reference/Snake-JavaScript-master/README.md
  kashyap-shah/Snake Game - JavaScript/Reference/Snake-JavaScript-master/audio/dead.mp3
  kashyap-shah/Snake Game - JavaScript/Reference/Snake-JavaScript-master/audio/down.mp3
  kashyap-shah/Snake Game - JavaScript/Reference/Snake-JavaScript-master/audio/eat.mp3
  kashyap-shah/Snake Game - JavaScript/Reference/Snake-JavaScript-master/audio/left.mp3
  kashyap-shah/Snake Game - JavaScript/Reference/Snake-JavaScript-master/audio/right.mp3
  kashyap-shah/Snake Game - JavaScript/Reference/Snake-JavaScript-master/audio/up.mp3
  kashyap-shah/Snake Game - JavaScript/Reference/Snake-JavaScript-master/img/food.png
  kashyap-shah/Snake Game - JavaScript/Reference/Snake-JavaScript-master/img/ground.png
  kashyap-shah/Snake Game - JavaScript/Reference/Snake-JavaScript-master/index.html
  kashyap-shah/Snake Game - JavaScript/Reference/Snake-JavaScript-master/snake.js
  kashyap-shah/Snake Game - JavaScript/Reference/Snake-JavaScript-master/snakeGame - starter template.rar
  kashyap-shah/Snake Game - JavaScript/audio/dead.mp3
  kashyap-shah/Snake Game - JavaScript/audio/down.mp3
  kashyap-shah/Snake Game - JavaScript/audio/eat.mp3
  kashyap-shah/Snake Game - JavaScript/audio/left.mp3
  kashyap-shah/Snake Game - JavaScript/audio/right.mp3
  kashyap-shah/Snake Game - JavaScript/audio/up.mp3
  kashyap-shah/Snake Game - JavaScript/game.js
  kashyap-shah/Snake Game - JavaScript/images/food.png
  kashyap-shah/Snake Game - JavaScript/images/ground.ai
  kashyap-shah/Snake Game - JavaScript/images/ground.png
  kashyap-shah/Snake Game - JavaScript/images/icon.png
  kashyap-shah/Snake Game - JavaScript/images/preloader.gif
  kashyap-shah/Snake Game - JavaScript/index.html
  kashyap-shah/Snake Game - JavaScript/style.css
  kashyap-shah/Snake_Game.gif
Labels: hacktoberfest2020

#41 kashyap-shah
  README.md
  kashyap-shah/Weather App - Javascript & API/app.js
  kashyap-shah/Weather App - Javascript & API/icons/01d.png
  kashyap-shah/Weather App - Javascript & API/icons/01n.png
  kashyap-shah/Weather App - Javascript & API/icons/02d.png
  kashyap-shah/Weather App - Javascript & API/icons/02n.png
  kashyap-shah/Weather App - Javascript & API/icons/03d.png
  kashyap-shah/Weather App - Javascript & API/icons/03n.png
  kashyap-shah/Weather App - Javascript & API/icons/04d.png
  kashyap-shah/Weather App - Javascript & API/icons/04n.png
  kashyap-shah/Weather App - Javascript & API/icons/09d.png
  kashyap-shah/Weather App - Javascript & API/icons/09n.png
  kashyap-shah/Weather App - Javascript & API/icons/10d.png
  kashyap-shah/Weather App - Javascript & API/icons/10n.png
  kashyap-shah/Weather App - Javascript & API/icons/11d.png
  kashyap-shah/Weather App - Javascript & API/icons/11n.png
  kashyap-shah/Weather App - Javascript & API/icons/13d.png
  kashyap-shah/Weather App - Javascript & API/icons/13n.png
  kashyap-shah/Weather App - Javascript & API/icons/50d.png
  kashyap-shah/Weather App - Javascript & API/icons/50n.png
  kashyap-shah/Weather App - Javascript & API/icons/chancerain.png
  kashyap-shah/Weather App - Javascript & API/icons/chancesnow.png
  kashyap-shah/Weather App - Javascript & API/icons/chancetstorms.png
  kashyap-shah/Weather App - Javascript & API/icons/clear.png
  kashyap-shah/Weather App - Javascript & API/icons/cloudy.png
  kashyap-shah/Weather App - Javascript & API/icons/fog.png
  kashyap-shah/Weather App - Javascript & API/icons/icon.png
  kashyap-shah/Weather App - Javascript & API/icons/mostlycloudy.png
  kashyap-shah/Weather App - Javascript & API/icons/nt_clear.png
  kashyap-shah/Weather App - Javascript & API/icons/preloader.gif
  kashyap-shah/Weather App - Javascript & API/icons/unknown.png
  kashyap-shah/Weather App - Javascript & API/index.html
  kashyap-shah/Weather App - Javascript & API/style.css
  kashyap-shah/Weather_App.gif
Labels: hacktoberfest2020

#42 whonamra
  whonamra/artworknamra.css
  whonamra/artworknamra.html
  whonamra/artworknamra.png
Labels: hacktoberfest2020

#43 HetGalia
  HetGalia/Pendulum/Pendulum.gif
  HetGalia/Pendulum/index.html
  HetGalia/Pendulum/style.css
  README.md
Labels: hacktoberfest2020

#50 omdhimar28
  README.md
  omdhimar28/Block.html
Labels: hacktoberfest2020

#30 imjp19
  README.md
  ezgif.com-gif-maker (2).gif
  imjp19/HOVER.gif
  imjp19/button-hover.html
  imjp19/change-color-clock.gif
  imjp19/color-change-clock.html
  imjp19/style3.css
Labels: Conflicts, hacktoberfest2020

#49 madhavtripathi05
  README.md
  madhavtripathi05/README.md
  madhavtripathi05/add.php
  madhavtripathi05/delete.php
  madhavtripathi05/index.php
  madhavtripathi05/init.php
  madhavtripathi05/mark.php
  madhavtripathi05/schema.txt
  madhavtripathi05/style.css
  madhavtripathi05/todos.gif
Labels: changes requested, hacktoberfest2020

#40 SmitShah090
  README.md
  SmitShah090/Music Player/Foodista
Labels: hacktoberfest-accepted, hacktoberfest2020

#29 MananJoshimj
  MananJoshimj/Animation3.html
  README.md
Labels: hacktoberfest-accepted, hacktoberfest2020

#56 anjali-patel21
  README.md
  anjali-patel21/glowing.html
Labels: hacktoberfest-accepted, hacktoberfest2020

#58 anjali-patel21
  README.md
  anjali-patel21/Hello_animation.html
Labels: hacktoberfest-accepted, hacktoberfest2020

#59 anjali-patel21
  README.md
  anjali-patel21/loading_animation.html
Labels: hacktoberfest-accepted, hacktoberfest2020

#60 iamdhrutipatel
  README.md
  iamdhrutipatel/animation_1.html
Labels: hacktoberfest-accepted, hacktoberfest2020

#61 iamdhrutipatel
  README.md
  iamdhrutipatel/animation_2.html
  iamdhrutipatel/animation_3.html
Labels: hacktoberfest-accepted, hacktoberfest2020

#32 thevrajshah
  README.md
  thevrajshah/VeggieBurger.html
Labels: changes requested, hacktoberfest2020

#64 het1912
  README.md
  het1912/ezgif.com-gif-maker (4).gif
  het1912/index.html
Labels: hacktoberfest-accepted, hacktoberfest2020

#70 PRIYANG012
  PRIYANG012/MLJsexamples/assets/bootstrap/css/bootstrap.min.css
  PRIYANG012/MLJsexamples/assets/bootstrap/css/style.css
  PRIYANG012/MLJsexamples/assets/bootstrap/css/style.scss
  PRIYANG012/MLJsexamples/assets/bootstrap/js/bootstrap.min.js
  PRIYANG012/MLJsexamples/assets/css/style.css
  PRIYANG012/MLJsexamples/assets/datasets/KNNDATASET.json
  PRIYANG012/MLJsexamples/assets/datasets/KNNData.json
  PRIYANG012/MLJsexamples/assets/datasets/myKNNDataset.json
  PRIYANG012/MLJsexamples/assets/images/bodypix.svg
  PRIYANG012/MLJsexamples/assets/images/imageclassification.svg
  PRIYANG012/MLJsexamples/assets/images/knn.svg
  PRIYANG012/MLJsexamples/assets/images/modelrep.png
  PRIYANG012/MLJsexamples/assets/images/posenet.svg
  PRIYANG012/MLJsexamples/assets/images/soundclass.svg
  PRIYANG012/MLJsexamples/assets/images/sticker.svg
  PRIYANG012/MLJsexamples/assets/images/sticker1r.svg
  PRIYANG012/MLJsexamples/assets/images/sticker2.svg
  PRIYANG012/MLJsexamples/assets/images/sticker2r.svg
  PRIYANG012/MLJsexamples/assets/images/sticker3.svg
  PRIYANG012/MLJsexamples/assets/images/upload.svg
  PRIYANG012/MLJsexamples/assets/images/word2vec.svg
  PRIYANG012/MLJsexamples/assets/js/bs-init.js
  PRIYANG012/MLJsexamples/assets/js/creative.js
  PRIYANG012/MLJsexamples/assets/js/dark.js
  PRIYANG012/MLJsexamples/assets/js/jquery.min.js
  PRIYANG012/MLJsexamples/assets/js/sketch2.js
  PRIYANG012/MLJsexamples/assets/js/sketch9.js
  PRIYANG012/MLJsexamples/assets/js/theme.js
  PRIYANG012/MLJsexamples/ezgif.com-gif-maker.gif
  PRIYANG012/MLJsexamples/index.html
  PRIYANG012/MLJsexamples/posenet.html
  PRIYANG012/MLJsexamples/readme.txt
  README.md
Labels: hacktoberfest-accepted, hacktoberfest2020

#69 Adding html and CSS styled card flip
  README.md
  ananthalakshmiragi/BasicCardFlip.gif
  ananthalakshmiragi/BasicCardFlip.html
Labels: hacktoberfest2020

#71 dawoodmalhi
  README.md
  dawoodmalhi/bg-image.jpg
  dawoodmalhi/index.html
  dawoodmalhi/sample-run.gif
  dawoodmalhi/script.js
  dawoodmalhi/style.css
Labels: hacktoberfest-accepted, hacktoberfest2020

#72 ananthalakshmiragi
  README.md
  ananthalakshmiragi/carouselWithText.gif
  ananthalakshmiragi/carouselWithText.html
Labels: hacktoberfest-accepted, hacktoberfest2020

#73 meetxpress
  README.md
  meetxpress/index.html
  meetxpress/main.css
  meetxpress/main.js
  meetxpress/search.gif
  search.gif
Labels: hacktoberfest-accepted, hacktoberfest2020
